CONST ALPAKA_ORIGINAL_WIDTH = 20;
CONST ALPAKA_ORIGINAL_HEIGHT = 28;
CONST ALPAKA_SCALE = 8;
CONST ALPAKA_WIDTH = ALPAKA_ORIGINAL_WIDTH * SCALE;
CONST ALPAKA_HEIGHT = ALPAKA_ORIGINAL_HEIGHT * SCALE;
CONST MOTHERSHIP_OPENING_LEFT  = 323;
CONST MOTHERSHIP_OPENING_RIGHT  = 955-ALPAKA_WIDTH;
