const GRAVITY = 0.00015;
const VY_MAX = 2;
const VY_SLOW = 0.3;

const ALPAKA_ORIGINAL_WIDTH = 20;
const ALPAKA_ORIGINAL_HEIGHT = 28;
const ALPAKA_SCALE = 4;
const ALPAKA_WIDTH = ALPAKA_ORIGINAL_WIDTH * ALPAKA_SCALE;
const ALPAKA_HEIGHT = ALPAKA_ORIGINAL_HEIGHT * ALPAKA_SCALE;

const MOTHERSHIP_OPENING_LEFT  = 323;
const MOTHERSHIP_OPENING_RIGHT  = 955-ALPAKA_WIDTH;
